export const LOAD_DOCUMENT = 'LOAD_DOCUMENT';

export const ON_ZOOM_IN = 'ON_ZOOM_IN';
export const ON_ZOOM_OUT = 'ON_ZOOM_OUT';

export const ON_PAGE_CHANGE = 'ON_PAGE_CHANGE';

export const ON_SEARCH_EXECUTE = 'ON_SEARCH_EXECUTE';
export const ON_SEARCH_COMPLETE = 'ON_SEARCH_COMPLETE';

export const ON_RESULT_SELECT = 'ON_RESULT_SELECT';